# Generated by Django 5.1 on 2024-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_grade_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_surname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_description',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_surname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
