# Generated by Django 5.1 on 2024-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_class_class_year_student_student_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
