# Generated by Django 5.1 on 2024-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_class_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
